(function(){
'use strict';Object.freeze({esVersion:6,assumingES6:!0,productionMode:!0,linkerVersion:"1.13.0",fileLevelThis:this});var h;function l(a){for(var b in a)return b}
function m(a){switch(typeof a){case "string":return"java.lang.String";case "number":return"number"===typeof a&&(a|0)===a&&1/a!==1/-0?a<<24>>24===a?"java.lang.Byte":a<<16>>16===a?"java.lang.Short":"java.lang.Integer":"number"!==typeof a||a===a&&Math.fround(a)!==a?"java.lang.Double":"java.lang.Float";case "boolean":return"java.lang.Boolean";case "undefined":return"java.lang.Void";default:return null===a?a.C():a instanceof n?"java.lang.Long":a&&a.$classData?a.$classData.name:null.D()}}var p=0,q=new WeakMap;
function aa(a){switch(typeof a){case "string":return r(a);case "number":t||(t=new u);var b=t;var c=a|0;c===a&&-Infinity!==1/a?a=c:(b.q[0]=a,a=(b.j[0]|0)^(b.j[1]|0));return a;case "bigint":b=0;for(a<BigInt(0)&&(a=~a);a!==BigInt(0);)b^=Number(BigInt.asIntN(32,a)),a>>=BigInt(32);return b;case "boolean":return a?1231:1237;case "undefined":return 0;case "symbol":return a=a.description,void 0===a?0:r(a);default:if(null===a)return 0;b=q.get(a);void 0===b&&(p=b=p+1|0,q.set(a,b));return b}}function v(){}
v.prototype.constructor=v;function w(){}w.prototype=v.prototype;v.prototype.p=function(){return aa(this)};v.prototype.l=function(){var a=this.p();return m(this)+"@"+(+(a>>>0)).toString(16)};v.prototype.toString=function(){return this.l()};function y(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=null}else this.a=a}y.prototype=new w;y.prototype.constructor=y;function z(){}z.prototype=y.prototype;
function A(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=!1}else this.a=a}A.prototype=new w;A.prototype.constructor=A;function B(a){this.a="number"===typeof a?new Uint16Array(a):a}B.prototype=new w;B.prototype.constructor=B;function C(a){this.a="number"===typeof a?new Int8Array(a):a}C.prototype=new w;C.prototype.constructor=C;function D(a){this.a="number"===typeof a?new Int16Array(a):a}D.prototype=new w;D.prototype.constructor=D;
function E(a){this.a="number"===typeof a?new Int32Array(a):a}E.prototype=new w;E.prototype.constructor=E;function F(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=h}else this.a=a}F.prototype=new w;F.prototype.constructor=F;function G(a){this.a="number"===typeof a?new Float32Array(a):a}G.prototype=new w;G.prototype.constructor=G;function H(a){this.a="number"===typeof a?new Float64Array(a):a}H.prototype=new w;H.prototype.constructor=H;
function I(){this.k=void 0;this.g=this.c=null;this.h=0;this.r=null;this.d="";this.e=this.f=void 0;this.name="";this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function J(a,b,c,d){var e=new I;e.c={};e.r=a;e.d=b;e.e=g=>g===e;e.name=c;e.isPrimitive=!0;e.isInstance=()=>!1;void 0!==d&&(e.f=K(e,d));return e}
function L(a,b,c,d){var e=new I,g=l(a);e.c=c;e.d="L"+b+";";e.e=f=>!!f.c[g];e.name=b;e.isInterface=!1;e.isInstance=d||(f=>!!(f&&f.$classData&&f.$classData.c[g]));return e}function K(a,b,c){var d=new I;b.prototype.$classData=d;var e="["+a.d;d.k=b;d.c={b:1,w:1,m:1};d.g=a;d.h=1;d.d=e;d.name=e;d.isArrayClass=!0;d.e=c||(g=>d===g);d.isInstance=g=>g instanceof b;return d}
function ba(){function a(f){if("number"===typeof f){this.a=Array(f);for(var k=0;k<f;k++)this.a[k]=null}else this.a=f}var b=M,c=new I;a.prototype=new z;a.prototype.constructor=a;var d=b.g||b,e=b.h+1;a.prototype.$classData=c;b="["+b.d;c.k=a;c.c={b:1,w:1,m:1};c.g=d;c.h=e;c.d=b;c.name=b;c.isArrayClass=!0;var g=f=>{var k=f.h;return k===e?d.e(f.g):k>e&&d===N};c.e=g;c.isInstance=f=>{f=f&&f.$classData;return!!f&&(f===c||g(f))};return c}var N=new I;N.c={b:1};N.d="Ljava.lang.Object;";N.e=a=>!a.isPrimitive;
N.name="java.lang.Object";N.isInstance=a=>null!==a;N.f=K(N,y,a=>{var b=a.h;return 1===b?!a.g.isPrimitive:1<b});v.prototype.$classData=N;J(void 0,"V","void",void 0);J(!1,"Z","boolean",A);J(0,"C","char",B);J(0,"B","byte",C);J(0,"S","short",D);J(0,"I","int",E);var ca=J(null,"J","long",F);J(0,"F","float",G);J(0,"D","double",H);function O(){}O.prototype=new w;O.prototype.constructor=O;O.prototype.$classData=L({s:0},"dev.papacarlo.Library$",{s:1,b:1});var P;
function u(){this.q=this.j=this.i=null;t=this;this.i=new ArrayBuffer(8);this.j=new Int32Array(this.i,0,2);new Float32Array(this.i,0,2);this.q=new Float64Array(this.i,0,1);this.j[0]=16909060;new Int8Array(this.i,0,8)}u.prototype=new w;u.prototype.constructor=u;u.prototype.$classData=L({x:0},"java.lang.FloatingPointBits$",{x:1,b:1});var t;function n(a,b){this.o=a;this.n=b}n.prototype=new w;n.prototype.constructor=n;n.prototype.p=function(){return this.o^this.n};
n.prototype.l=function(){Q||(Q=new R);var a=this.o,b=this.n;return b===a>>31?""+a:0>b?"-"+S(-a|0,0!==a?~b:-b|0):S(a,b)};n.prototype.$classData=L({t:0},"org.scalajs.linker.runtime.RuntimeLong",{t:1,b:1});
function S(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+(Math.clz32(1E9)|0)|0)-(0!==b?Math.clz32(b)|0:32+(Math.clz32(a)|0)|0)|0,d=c,e=0===(32&d)?1E9<<d:0;d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d;var g=a,f=b;for(a=b=0;0<=c&&0!==(-2097152&f);){var k=g,x=f,da=e,V=d;if(x===V?(-2147483648^k)>=(-2147483648^da):(-2147483648^x)>=(-2147483648^V))k=f,x=d,f=g-e|0,k=(-2147483648^f)>(-2147483648^g)?-1+(k-x|0)|0:k-x|0,g=f,f=k,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;k=d>>>1|0;e=e>>>1|0|d<<31;d=k}c=
f;if(0===c?-1147483648<=(-2147483648^g):-2147483648<=(-2147483648^c))c=4294967296*f+ +(g>>>0),g=c/1E9,e=g/4294967296|0,d=b,b=g=d+(g|0)|0,a=(-2147483648^g)<(-2147483648^d)?1+(a+e|0)|0:a+e|0,g=c%1E9|0;c=""+g;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length)+c}return b}function R(){}R.prototype=new w;R.prototype.constructor=R;R.prototype.$classData=L({u:0},"org.scalajs.linker.runtime.RuntimeLong$",{u:1,b:1});var Q;function T(){}T.prototype=new w;T.prototype.constructor=T;function U(){}
U.prototype=T.prototype;T.prototype.l=function(){return"\x3cfunction1\x3e"};function W(){}W.prototype=new w;W.prototype.constructor=W;W.prototype.$classData=L({y:0},"scala.scalajs.js.Any$",{y:1,b:1,I:1,J:1});var X;function Y(a){this.A=a}Y.prototype=new U;Y.prototype.constructor=Y;Y.prototype.$classData=L({z:0},"scala.scalajs.runtime.AnonFunction1",{z:1,K:1,b:1,B:1});function r(a){for(var b=0,c=1,d=-1+a.length|0;0<=d;)b=b+Math.imul(a.charCodeAt(d),c)|0,c=Math.imul(31,c),d=-1+d|0;return b}
var M=L({v:0},"java.lang.String",{v:1,b:1,m:1,F:1,E:1,G:1,H:1},a=>"string"===typeof a);h=new n(0,0);ca.r=h;M.f||(M.f=ba());new M.f.k([]);P||(P=new O);var ea=new Y(()=>{0<+document.documentElement.scrollTop?document.querySelector(".banner").classList.add("collapsed"):document.querySelector(".banner").classList.remove("collapsed")}),Z=document,fa=Z.addEventListener;X||(X=new W);fa.call(Z,"scroll",function(a,b){return c=>(0,b.A)(c)}(X,ea));
}).call(this);
//# sourceMappingURL=main.js.map
